### ISSUE TITLE
Running_Issue

### ISSUE THREAD

**Issue by aamir1999** [RajneeshSingh007/College-Management--Android-App#6]
In which Software we can run this project?

**Comment by ace26597** [comment]
Android Studio or eclipse IDE.
I'd prefer android studio.
And you can use XAMPP or WAMP for database and PHP files or online web hosting

**Comment by aamir1999** [comment]
Bro thank you...But one question more how to configure wapm to work to work on phone.?

**Comment by aamir1999** [comment]
org.gradle.api.UncheckedIOException: Failed to capture snapshot of output files for task ':app:transformDexArchiveWithDexMergerForDebug' property 'streamOutputFolder' during up-to-date check.
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskFiles(CacheBackedTaskHistoryRepository.java:333)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.updateExecution(CacheBackedTaskHistoryRepository.java:183)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$200(CacheBackedTaskHistoryRepository.java:61)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.updateCurrentExecution(CacheBackedTaskHistoryRepository.java:121)
	at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.snapshotAfterTaskExecution(DefaultTaskArtifactStateRepository.java:178)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:78)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:59)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:128)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:46)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$ExecuteTasks.run(DefaultGradleLauncher.java:314)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.initialization.DefaultGradleLauncher.runTasks(DefaultGradleLauncher.java:204)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:134)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:109)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedBuildActionRunner.run(ClientProvidedBuildActionRunner.java:62)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:57)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:69)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:30)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.UncheckedIOException: Failed to create MD5 hash for file 'C:\Desktop\College-Management-Android-App-master\Slrtce\app\build\intermediates\transforms\dexMerger\debug\1\classes.dex'.
	at org.gradle.internal.hash.DefaultFileHasher.hash(DefaultFileHasher.java:45)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.snapshot(CachingFileHasher.java:88)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.snapshot(CachingFileHasher.java:75)
	at org.gradle.api.internal.changedetection.state.CachingFileHasher.hash(CachingFileHasher.java:61)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.fileSnapshot(DefaultFileSystemSnapshotter.java:190)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.access$600(DefaultFileSystemSnapshotter.java:54)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$FileVisitorImpl.visitFile(DefaultFileSystemSnapshotter.java:224)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:86)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker$1.visitFile(Jdk7DirectoryWalker.java:59)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at org.gradle.api.internal.file.collections.jdk7.Jdk7DirectoryWalker.walkDir(Jdk7DirectoryWalker.java:59)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.walkDir(DirectoryFileTree.java:155)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visitFrom(DirectoryFileTree.java:133)
	at org.gradle.api.internal.file.collections.DirectoryFileTree.visit(DirectoryFileTree.java:118)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.doSnapshot(DefaultFileSystemSnapshotter.java:166)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.access$500(DefaultFileSystemSnapshotter.java:54)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$4.create(DefaultFileSystemSnapshotter.java:148)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter$4.create(DefaultFileSystemSnapshotter.java:142)
	at org.gradle.cache.internal.ProducerGuard$StripedProducerGuard.guardByKey(ProducerGuard.java:115)
	at org.gradle.api.internal.changedetection.state.DefaultFileSystemSnapshotter.snapshotDirectoryTree(DefaultFileSystemSnapshotter.java:142)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitDirectoryTree(AbstractFileCollectionSnapshotter.java:98)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter$FileCollectionVisitorImpl.visitCollection(AbstractFileCollectionSnapshotter.java:82)
	at org.gradle.api.internal.file.AbstractFileCollection.visitRootElements(AbstractFileCollection.java:234)
	at org.gradle.api.internal.file.CompositeFileCollection.visitRootElements(CompositeFileCollection.java:185)
	at org.gradle.api.internal.changedetection.state.AbstractFileCollectionSnapshotter.snapshot(AbstractFileCollectionSnapshotter.java:53)
	at org.gradle.api.internal.changedetection.state.DefaultGenericFileCollectionSnapshotter.snapshot(DefaultGenericFileCollectionSnapshotter.java:38)
	at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskFiles(CacheBackedTaskHistoryRepository.java:331)
	... 111 more
Caused by: java.io.FileNotFoundException: C:\Desktop\College-Management-Android-App-master\Slrtce\app\build\intermediates\transforms\dexMerger\debug\1\classes.dex (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.gradle.internal.hash.DefaultFileHasher.hash(DefaultFileHasher.java:38)
	... 137 more


i found this type of error at run time

**Comment by aamir1999** [comment]
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.

I found this type of warning at Run Time. How can i solve these?

**Comment by ace26597** [comment]
Did you change address in contsants file?
You need to change address for app to use and implement PHP files and database.
If you are using wamp then you can put IP address/filename.php.
And if you are using webhosting then you can put URL..with wamp you need to be connected to same network or same WiFi as we are working on private IP address

**Comment by aamir1999** [comment]
Yes i did but at running time i found this type of error->
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation'.
Please can you run and send the zip file in mail id. I think something is wrong in gridle.build file. Please send me the zip file.
Email: amallick546@gmail.com

**Comment by RajneeshSingh007** [comment]
@aamir1999 Hello,
It's warning you can ignore  and also make sure run test mail server tool for email verification.

**Comment by mkpal456** [comment]
I am getting the following error when i try to sync it with gradle files. What to do , i searched on internet applied all the solutions stated there but in vain.

Could not find com.android.tools.build:gradle:3.0.1.
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
Required by:
    project :
Open File

**Comment by RajneeshSingh007** [comment]
Hello,
Please, update your android studio.
also, if library not available via dependency url... pick from github and
import manually.

**Comment by mkpal456** [comment]
Android studio is updated already how to pick dependency url from github.

**Comment by RajneeshSingh007** [comment]
@mkpal456
check Picker library from vikramkakkar https://github.com/vikramkakkar/SublimePicker
and Android networking library.

**Comment by mkpal456** [comment]
I am unable to sign up in your app can you please give me your mail id or
contact number.

**Comment by RajneeshSingh007** [comment]
it's issue of mail verification... please check mail server smtp software.
my email id : manish.rajneesh@gmail.com

**Comment by mkpal456** [comment]
i am unable to sign up please tell me the step by step process.

**Comment by krsnajeeva** [comment]
i am sign in any of account like student,teacher,others but still loading nothing to show.. how to fix it

**Comment by krsnajeeva** [comment]
i am run the app in android emulator

**Comment by seanjsm** [comment]
I've successfully build the app .I can register and login but when you login where you select your course It wont save and just crash and when I launch the app again it is logged in but the appdrawer wont work. pls help

**Comment by RajneeshSingh007** [comment]
@seanjsm...Please, share logcat.
Also, course selection is only available for branch (cmpn) and be(fourth year)

**Comment by seanjsm** [comment]
how? I'm using my phone not the emulator and my phone is not rooted I cant get the logs

**Comment by RajneeshSingh007** [comment]
@seanjsm
1. Enable usb debugging in your phone settings.
2. Connect to your pc and open project
3. Run app and open logcat tab in the android studio.

**Comment by seanjsm** [comment]
this is what I got 
01-19 00:09:58.775 2684-2684/? E/Zygote: isWhitelistProcess - Process is Whitelisted
01-19 00:09:58.776 2684-2684/? E/libpersona: scanKnoxPersonas
01-19 00:09:58.777 2684-2684/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory



01-19 00:08:28.645 1492-1492/com.sssa.slrtce D/ViewRootImpl@56f0548[MainActivity]: ViewPostIme pointer 0
01-19 00:08:28.697 1492-1492/com.sssa.slrtce D/ViewRootImpl@56f0548[MainActivity]: ViewPostIme pointer 1
01-19 00:08:28.723 1492-1492/com.sssa.slrtce I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
01-19 00:08:28.725 1492-1492/com.sssa.slrtce I/chatty: uid=10328(u0_a328) com.sssa.slrtce identical 1 line
01-19 00:08:28.745 1492-1492/com.sssa.slrtce I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.


01-19 00:10:20.945 2684-2708/com.sssa.slrtce I/OpenGLRenderer: destroy mLayerUpdateQueue is not empty, size = 1
    name = PopupWindow$PopupBackgroundView, size (784, 192)
01-19 00:10:20.976 2684-2684/com.sssa.slrtce E/ViewRootImpl: sendUserActionEvent() returned.
01-19 00:10:20.998 2684-2684/com.sssa.slrtce D/ViewRootImpl@4da03ba[Toast]: setView = android.widget.LinearLayout{9d2726b V.E...... ......I. 0,0-0,0} TM=true MM=false
01-19 00:10:20.999 2684-2684/com.sssa.slrtce V/Toast: Text: Mogg in android.widget.Toast$TN@73981c8

**Comment by seanjsm** [comment]
I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
I guess this is the problem  . every time press the navigationdrawer it appears on the log

**Comment by RajneeshSingh007** [comment]
@seanjsm try to capture full logcat.
that's is not errror.

**Comment by seanjsm** [comment]
01-24 09:12:09.099 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:12:09.133 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:12:11.361 28280-17106/? E/SPPClientService: [e] Push Channel Exception : java.net.SocketTimeoutException: failed to connect to /52.18.207.163 (port 5223) from /192.168.22.5 (port 56545) after 15000ms
01-24 09:12:11.375 28280-17106/? E/SPPClientService: [a] Fail connect to server : Fail connect to server.
    [g] handleMessage. ConnectionException:fail connect to server
01-24 09:12:11.380 28280-17106/? E/SPPClientService: [g] processError. message.arg1:-1472288436,  internalErrorCode:-104
01-24 09:12:11.387 28280-17105/? E/SPPClientService: [b] SharedConstants.WHAT_INTERNAL_ERROR
01-24 09:12:11.392 28280-17105/? E/SPPClientService: [b] handleError->resultCode: INITIALIZATION_FAIL(-104)
01-24 09:12:11.396 28280-17105/? E/SPPClientService: [a] [ConnectionManager] Connection is already disconnected.
    [b] null
    [b] [ReInit] Retry Count : 14
01-24 09:12:12.280 5270-5404/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 3ms lastUpdatedAfter : 60050 ms mFlush_time_threasold : 2000 mCurrentSize : 659
01-24 09:12:21.448 28280-28280/? E/SPPClientService: [[PushClientService]] reqType : 0
01-24 09:12:21.477 28280-28280/? E/SPPClientService: [[PushClientService]] F:false, D:false, E:false, T:false, S:false, R:false
01-24 09:12:21.497 28280-28280/? E/SPPClientService: [a] [ConnectionManager] Connection is already disconnected.
    [b] null
01-24 09:12:25.524 4815-18004/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
01-24 09:12:27.046 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:12:27.129 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:12:29.219 3652-3677/? E/BatteryStatsService: no controller energy info supplied
01-24 09:12:29.233 3652-3677/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
01-24 09:12:29.242 3652-3674/? E/KernelUidCpuTimeReader: Failed to read uid_cputime: /proc/uid_cputime/show_uid_stat (No such file or directory)
01-24 09:12:29.303 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:12:33.583 3652-4156/? E/Watchdog: !@Sync 1289 [2019-01-24 09:12:33.583]
01-24 09:12:41.557 28280-17106/? E/SPPClientService: [c] [PROV CHANNEL] exceptionCaught : java.net.UnknownHostException: velb-pew1gld-1366174266.eu-west-1.elb.amazonaws.com
01-24 09:12:41.558 28280-17106/? E/SPPClientService: [a] Fail connect to server : Fail connect to server.
01-24 09:12:41.566 28280-17106/? E/SPPClientService: [g] processError. message.arg1:281504792,  internalErrorCode:-103
01-24 09:12:41.581 28280-17105/? E/SPPClientService: [b] SharedConstants.WHAT_INTERNAL_ERROR
01-24 09:12:41.592 28280-17105/? E/SPPClientService: [b] handleError->resultCode: PROVISIONING_FAIL(-103)
    [b] redoProvisioning()
01-24 09:12:45.559 4815-18025/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
01-24 09:12:45.604 4815-18025/? E/WakeLock: GCM_CONN_ALARM release without a matched acquire!
01-24 09:12:49.403 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:12:49.502 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info1
01-24 09:12:49.507 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info2
01-24 09:12:49.513 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info3
01-24 09:12:49.518 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info4
01-24 09:12:49.523 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info5
01-24 09:12:49.528 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info6
01-24 09:12:49.546 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info7
01-24 09:12:49.550 3652-3780/? E/TLC_TIMA_PKM_initialize: tima_pkm : /system/etc/tima/kern_sec_info8
01-24 09:12:59.408 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:13:03.601 3652-4156/? E/Watchdog: !@Sync 1290 [2019-01-24 09:13:03.601]
01-24 09:13:11.655 28280-17106/? E/SPPClientService: [c] [PROV CHANNEL] exceptionCaught : java.net.UnknownHostException: velb-pew1gld-1366174266.eu-west-1.elb.amazonaws.com
    [a] Fail connect to server : Fail connect to server.
01-24 09:13:11.660 28280-17106/? E/SPPClientService: [g] processError. message.arg1:1636081588,  internalErrorCode:-103
01-24 09:13:11.667 28280-17105/? E/SPPClientService: [b] SharedConstants.WHAT_INTERNAL_ERROR
01-24 09:13:11.678 28280-17105/? E/SPPClientService: [b] handleError->resultCode: PROVISIONING_FAIL(-103)
    [b] redoProvisioning()
01-24 09:13:12.407 5270-5404/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 2ms lastUpdatedAfter : 60126 ms mFlush_time_threasold : 2000 mCurrentSize : 659
01-24 09:13:19.534 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:13:19.569 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:13:20.674 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:13:33.616 3652-4156/? E/Watchdog: !@Sync 1291 [2019-01-24 09:13:33.616]
01-24 09:13:36.282 16999-17038/? E/PlayCommon: [2480] com.google.android.play.b.x.a(20): Failed to connect to server for server timestamp: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
01-24 09:13:36.305 16999-17038/? E/PlayCommon: [2480] com.google.android.play.b.g.a(360): Failed to connect to server: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
01-24 09:13:38.072 17360-18091/? E/ActivityThread: Failed to find provider info for com.samsung.android.bixby.agent.settings
01-24 09:13:38.100 4836-4836/? E/PBSessionCacheImpl: sessionId[21270501152800618] not persisted.
01-24 09:13:38.213 5085-18092/? E/Launcher.WallpaperUtils: check bitmap.recycle() on releaseWallpaperDrawable
01-24 09:13:39.713 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:13:39.802 5085-5085/? E/ProActivieLaunch: Sending Broadcast
01-24 09:13:39.808 3652-3652/? E/ActivityManager: TouchDown intent received, starting ActiveLaunch
01-24 09:13:39.962 17360-18097/? E/ActivityThread: Failed to find provider info for com.samsung.android.bixby.agent.settings
01-24 09:13:51.762 28280-17106/? E/SPPClientService: [c] [PROV CHANNEL] exceptionCaught : java.net.UnknownHostException: velb-pew1gld-1366174266.eu-west-1.elb.amazonaws.com
01-24 09:13:51.763 28280-17106/? E/SPPClientService: [a] Fail connect to server : Fail connect to server.
01-24 09:13:51.767 28280-17106/? E/SPPClientService: [g] processError. message.arg1:-1351371327,  internalErrorCode:-103
01-24 09:13:51.773 28280-17105/? E/SPPClientService: [b] SharedConstants.WHAT_INTERNAL_ERROR
01-24 09:13:51.785 28280-17105/? E/SPPClientService: [b] handleError->resultCode: PROVISIONING_FAIL(-103)
    [b] redoProvisioning()
01-24 09:13:58.219 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:13:59.816 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:14:00.030 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:14:03.629 3652-4156/? E/Watchdog: !@Sync 1292 [2019-01-24 09:14:03.629]
01-24 09:14:05.580 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:14:09.846 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:14:11.206 3652-3869/? E/SemContext.CaeProvider: setAttribute() : attribute is null!
01-24 09:14:11.231 3205-3745/? E/Sensors: inject_scontext_data: New ssp_data_injection_fd(27)
01-24 09:14:12.504 5270-5404/? E/ContactsProvider_EventLog: Flush buffer to file cnt : 1 size : 1Kb duration : 1ms lastUpdatedAfter : 60096 ms mFlush_time_threasold : 2000 mCurrentSize : 659
01-24 09:14:16.040 18126-18126/? E/Zygote: isWhitelistProcess - Process is Whitelisted
01-24 09:14:16.041 18126-18126/? E/libpersona: scanKnoxPersonas
01-24 09:14:16.042 18126-18126/? E/libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
01-24 09:14:25.617 4815-18113/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
01-24 09:14:29.997 3652-3673/? E/memtrack: Couldn't load memtrack module
01-24 09:14:30.036 5133-5133/? E/CatchNotificationsService: Invalid notification data
01-24 09:14:33.642 3652-4156/? E/Watchdog: !@Sync 1293 [2019-01-24 09:14:33.642]
is this it?
 @RajneeshSingh007
